name: coffee_lover
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  appinio_swiper: ^2.1.1
  bloc: ^8.1.3
  bloc_test: ^9.1.7
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.4
  http: ^1.2.1
  intl: ^0.19.0

  # flutter_gen: any
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

icons_launcher:
  image_path: "assets/icon/coffee_icon.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lottie/
